apiVersion: v2
name: streamspace
description: Kubernetes-native multi-user platform for streaming containerized applications to web browsers
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - streamspace
  - vnc
  - containers
  - multi-user
  - streaming
  - kubernetes
  - browser-based
  - remote-desktop
home: https://github.com/streamspace/streamspace
sources:
  - https://github.com/streamspace/streamspace
maintainers:
  - name: StreamSpace Team
    email: team@streamspace.io
icon: https://streamspace.io/logo.png
kubeVersion: ">=1.19.0-0"
