# digiKam - Professional photo management software
# Category: Design & Graphics
# Base Image: lscr.io/linuxserver/digikam:latest
---
apiVersion: stream.streamspace.io/v1alpha1
kind: Template
metadata:
  name: digikam
  namespace: streamspace
  labels:
    app.kubernetes.io/name: digikam
    app.kubernetes.io/component: template
    streamspace.io/category: design-graphics
spec:
  displayName: digiKam
  description: Professional photo management software
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/digikam-logo.png
  baseImage: lscr.io/linuxserver/digikam:latest
  defaultResources:
    requests:
      memory: 3Gi
      cpu: 1500m
    limits:
      memory: 3Gi
      cpu: 3000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - digikam
  - design-&-graphics
