# Audacity - Free audio editor and recording software
# Category: Audio & Video
# Base Image: lscr.io/linuxserver/audacity:latest
---
apiVersion: stream.streamspace.io/v1alpha1
kind: Template
metadata:
  name: audacity
  namespace: streamspace
  labels:
    app.kubernetes.io/name: audacity
    app.kubernetes.io/component: template
    streamspace.io/category: audio-video
spec:
  displayName: Audacity
  description: Free audio editor and recording software
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/audacity-logo.png
  baseImage: lscr.io/linuxserver/audacity:latest
  defaultResources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  - Audio
  tags:
  - audacity
  - audio-&-video
